require "rake/testtask"
require "./src/print_results.rb"

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/name_processor_test.rb']
  t.verbose = true
end

desc "Apply functions and print results"
task :print_results do
  PrintResults.new().print_results
  
end


task :default=> [:test, :print_results]